//! gdb-gen - GDB exploit脚本生成器
//! 生成基础/格式串/堆/attach 调试脚本, 严格校验参数

use clap::Parser;
use common::{exit, finish, Mode, Out};
use serde::Serialize;
use std::path::Path;
use std::process::ExitCode;

const DOC: &str = "pwn-gdb: GDB exploit脚本生成器
用法:
    pwn-gdb <binary> [libc.so]          # 生成exploit辅助脚本
    pwn-gdb --fmt <binary>              # 生成格式串调试脚本
    pwn-gdb --heap <binary>             # 生成堆调试脚本
    pwn-gdb --attach <pid>              # 生成attach脚本
";

#[derive(Parser, Debug)]
#[command(
    name = "gdb-gen",
    version,
    about = "GDB exploit脚本生成器",
    long_about = "用法:\n    gdb-gen <binary> [libc.so]          # 生成exploit辅助脚本\n    gdb-gen --fmt <binary>              # 生成格式串调试脚本\n    gdb-gen --heap <binary>             # 生成堆调试脚本\n    gdb-gen --attach <pid>              # 生成attach脚本\n\n未知参数由 clap 严格校验并报错, 不会生成垃圾文件。",
    after_help = "退出码: 0=成功 1=无结果 2=用法错误 3=运行错误"
)]
struct Args {
    /// 目标二进制 (基本模式)
    #[arg(value_name = "BINARY")]
    binary: Option<String>,

    /// libc.so 路径 (可选)
    #[arg(value_name = "LIBC")]
    libc: Option<String>,

    /// 生成格式串调试脚本
    #[arg(long, num_args = 0..=1, default_missing_value = "vuln", value_name = "BINARY")]
    fmt: Option<String>,

    /// 生成堆调试脚本
    #[arg(long, num_args = 0..=1, default_missing_value = "vuln", value_name = "BINARY")]
    heap: Option<String>,

    /// 生成attach脚本
    #[arg(long, num_args = 0..=1, default_missing_value = "12345", value_name = "PID")]
    attach: Option<String>,

    /// JSON 输出
    #[arg(long)]
    json: bool,
}

#[derive(Serialize)]
#[serde(tag = "mode", rename_all = "kebab-case")]
enum Report {
    Basic {
        binary: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        libc: Option<String>,
        output: String,
        content: String,
    },
    Fmt {
        binary: String,
        output: String,
        content: String,
    },
    Heap {
        binary: String,
        output: String,
        content: String,
    },
    Attach {
        pid: String,
        output: String,
        content: String,
    },
}

fn basename(path: &str) -> String {
    Path::new(path)
        .file_name()
        .map(|s| s.to_string_lossy().to_string())
        .unwrap_or_else(|| path.to_string())
}

fn gen_basic(binary: &str, libc: Option<&str>) -> String {
    let filename = format!("{}.gdb", basename(binary));
    let func = "main";
    let addr = "601000";
    let mut content = format!(
        r#"#!/usr/bin/env gdb
# Auto-generated by pwn-gdb
# Usage: gdb -x {filename}

set disassembly-flavor intel
set pagination off
set follow-fork-mode child
set detach-on-fork off

# ===== 断点 =====
# break main
# break *main+XX
# break {func}

# ===== 通用显示 =====
define hook-stop
    printf "\n===== Registers =====\n"
    info registers
    printf "\n===== Stack (8 words) =====\n"
    x/8gx $rsp
    printf "\n===== Code (at rip) =====\n"
    x/3i $rip
end

# ===== 辅助命令 =====
define got
    info proc mappings
    # 修改为你的GOT地址
    # x/2gx 0x{addr}
end

define stack
    x/20gx $rsp
end

define heap
    # 需要pwndbg/gef
    heap
end

define libc
    info proc mappings
    # 修改为实际libc加载地址
    # set $libc = 0x{addr}
end
"#
    );

    if let Some(l) = libc {
        content += &format!(
            r#"
# ===== libc 信息 =====
# libc: {l}
# set $system = $libc + 0x4f550
# set $binsh  = $libc + 0x1b3e1a
# set $malloc = $libc + 0x8fbd0
"#
        );
    }

    content += r#"
# ===== 覆写GOT示例 =====
# set *0x601020 = 0x7ffff7a5c000
# 用格式串: printf "%8$lx" 查看第8个参数

# ===== 运行 =====
# starti       # 从入口点开始
# context      # pwndbg上下文
# vis_heap_chunks  # 堆可视化(pwndbg)

# b *main
# run
"#;
    content
}

fn gen_fmt(binary: &str) -> String {
    format!(
        r#"#!/usr/bin/env gdb
# 格式串调试脚本 - {binary}

set disassembly-flavor intel
set pagination off

# ===== 格式串参数偏移检测 =====
# 先运行到printf/puts处, 输入 AAAA%p.%p.%p... 查看偏移
define fmt_scan
    # 在printf调用处断点
    # b *printf
    # r
    # 然后输入: AAAA%6$p.%7$p.%8$p.%9$p
    # 观察哪个位置出现 0x41414141
    echo 输入格式串: AAAA%6$p.%7$p.%8$p.%9$p\n
end

# ===== 格式串读内存 =====
define fmt_leak
    # set $target = 0xADDR
    # printf "%6$s\n", $target
    echo 用法: fmt_leak 0xADDR\n
end

# ===== 格式串写内存 =====
define fmt_write
    # 用%hhn逐字节写
    # printf "%XXc%8$hhn%YYc%9$hhn...", *addr1, *addr2, ...
    echo 用法: 用 pwn-fmt 生成payload, 粘贴到输入\n
end

# ===== 信息泄露 =====
define leak
    # 泄露canary: 看栈上某个固定偏移
    x/gx $rsp+OFFSET
    # 泄露libc: 泄露__libc_start_main返回地址
    # x/gx $rsp+OFFSET
end
"#
    )
}

fn gen_heap(binary: &str) -> String {
    format!(
        r#"#!/usr/bin/env gdb
# 堆调试脚本 - {binary}
# 推荐配合 pwndbg 或 gef

set disassembly-flavor intel
set pagination off

# ===== 堆信息 =====
define heap_info
    info proc mappings
    # pwndbg: heap
    # gef: heap bins
end

# ===== 堆块查看 =====
define chunk
    # x/32gx $rdi-0x10
    # 查看 chunk header: [size] [prev_size]
    echo 用法: chunk <address>\n
    x/16gx $arg0-0x10
end

# ===== fastbin 查看 =====
define fastbins
    # pwndbg: fastbins
    # gef: heap fastbins
    echo pwndbg: fastbins\n
    echo gef: heap fastbins\n
end

# ===== tcache 查看 =====
define tcache
    echo pwndbg: tcache\n
    echo gef: heap tcache\n
end

# ===== unsorted bin 查看 =====
define unsorted
    echo pwndbg: bins\n
    echo gef: heap unsorted\n
end

# ===== 常用堆断点 =====
# b __libc_malloc
# b __libc_free
# b __memcpy_avx_unaligned_erms
# b _int_malloc
"#
    )
}

fn gen_attach(pid: &str) -> String {
    format!(
        r#"#!/usr/bin/env gdb
# Attach到进程 {pid}

set disassembly-flavor intel
set pagination off
set follow-fork-mode child

attach {pid}

# 设置断点
# break main
# break read
# break write

# 继续执行
continue
"#
    )
}

fn main() -> ExitCode {
    common::reset_sigpipe();
    let args = Args::parse();
    let out = Out::new(Mode::from_flag(args.json));

    let modes = [
        args.fmt.is_some(),
        args.heap.is_some(),
        args.attach.is_some(),
    ]
    .iter()
    .filter(|b| **b)
    .count();

    if modes > 1 {
        out.error("参数冲突: --fmt/--heap/--attach 一次只能使用一个");
        return finish(exit::USAGE);
    }
    if modes > 0 && args.binary.is_some() {
        out.error("参数冲突: 模式选项与位置参数 <BINARY> 不能同时使用");
        return finish(exit::USAGE);
    }
    if modes == 0 && args.binary.is_none() {
        if out.json() {
            out.error("no command specified");
        } else {
            println!("{DOC}");
        }
        return finish(exit::USAGE);
    }

    let (report, outfile) = if let Some(binary) = &args.fmt {
        let outfile = format!("pwn_fmt_{}.gdb", basename(binary));
        let content = gen_fmt(binary);
        (
            Report::Fmt {
                binary: binary.clone(),
                output: outfile.clone(),
                content,
            },
            outfile,
        )
    } else if let Some(binary) = &args.heap {
        let outfile = format!("pwn_heap_{}.gdb", basename(binary));
        let content = gen_heap(binary);
        (
            Report::Heap {
                binary: binary.clone(),
                output: outfile.clone(),
                content,
            },
            outfile,
        )
    } else if let Some(pid) = &args.attach {
        let outfile = format!("pwn_attach_{pid}.gdb");
        let content = gen_attach(pid);
        (
            Report::Attach {
                pid: pid.clone(),
                output: outfile.clone(),
                content,
            },
            outfile,
        )
    } else {
        let binary = args.binary.as_deref().expect("binary");
        let outfile = format!("pwn_{}.gdb", basename(binary));
        let content = gen_basic(binary, args.libc.as_deref());
        (
            Report::Basic {
                binary: binary.to_string(),
                libc: args.libc.clone(),
                output: outfile.clone(),
                content,
            },
            outfile,
        )
    };

    let content = match &report {
        Report::Basic { content, .. }
        | Report::Fmt { content, .. }
        | Report::Heap { content, .. }
        | Report::Attach { content, .. } => content.clone(),
    };

    if let Err(e) = std::fs::write(&outfile, &content) {
        out.error(&format!("cannot write {outfile}: {e}"));
        return finish(exit::ERROR);
    }

    out.emit(
        || {
            println!("[*] GDB script generated: {outfile}");
            println!("[*] Usage: gdb -x {outfile}");
            println!("    or source {outfile} in gdb");
            println!("\n{}", "=".repeat(50));
            println!("{content}");
        },
        &report,
    );
    out.info(&format!("[*] Written to {outfile}"));

    finish(exit::OK)
}
