[package]
name = "xssserv"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
common = { workspace = true }
clap = { workspace = true }
colored = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[[bin]]
name = "xssserv"
path = "src/main.rs"
